export const enum UserFlags {
    STAFF = 1 << 0,
    PARTNER = 1 << 1,
    HYPESQUAD = 1 << 2,

    BUG_HUNTER_LEVEL_1 = 1 << 3,

    MFA_SMS = 1 << 4,
    PREMIUM_PROMO_DISMISSED = 1 << 5,

    HYPESQUAD_BRAVERY = 1 << 6,
    HYPESQUAD_BRILLIANCE = 1 << 7,
    HYPESQUAD_BALANCE = 1 << 8,

    EARLY_NITRO_BADGE = 1 << 9,
    IS_TEAM = 1 << 10,

    INTERNAL_APPLICATION = 1 << 11,
    SYSTEM = 1 << 12,
    HAS_UNREAD_URGENT_MESSAGES = 1 << 13,
    
    BUG_HUNTER_LEVEL_2 = 1 << 14,

    UNDERAGE_DELETED = 1 << 15,

    VERIFIED_BOT = 1 << 16,
    VERIFIED_DEVELOPER = 1 << 17,
    CERTIFIED_MODERATOR = 1 << 18,

    BOT_HTTP_INTERACTIONS = 1 << 19,
    SPAMMER = 1 << 20,
    DISABLE_NITRO = 1 << 21,
    
    ACTIVE_DEVELOPER = 1 << 22,

    // 22 ... 33 unknown

    HIGH_GLOBAL_RATELIMIT = 1 << 33,

    DELETED = 1 << 34,
    DISABLED_FOR_SUSPICIOUS_ACTIVITY = 1 << 35,
    SELF_DELETED = 1 << 36,
    PREMIUM_DISCRIMINATOR = 1 << 37,

    USED_DESKTOP_CLIENT = 1 << 38,
    USED_WEB_CLIENT = 1 << 39,
    USED_MOBILE_CLIENT = 1 << 40,

    DISABLED = 1 << 41,

    VERIFIED_EMAIL = 1 << 43,
    QUARANTINED = 1 << 44,

    STAFF_COLLABORATOR = 1 << 50,
    STAFF_RESTRICTED_COLLABORATOR = 1 << 51
}

export const enum ApplicationFlags {
    NONE = 0,
    RELEASED = 1 << 1,
    MANAGED_EMOJI = 1 << 2,
    IN_APP_PURCHASES = 1 << 3,
    CAN_CREATE_GROUP_DMS = 1 << 4,
    RPC_PRIVATE_BETA = 1 << 5,
    USES_AUTOMOD_BADGE = 1 << 6,

    ALLOW_ASSETS = 1 << 8,
    ALLOW_SPECTATING = 1 << 9,
    ALLOW_JOINING = 1 << 10,
    RPC_CONNECTED = 1 << 11,
    GATEWAY_PRESENCE = 1 << 12,
    GATEWAY_PRESENCE_LIMITED = 1 << 13,
    GATEWAY_GUILD_MEMBERS = 1 << 14,
    GATEWAY_GUILD_MEMBERS_LIMITED = 1 << 15,
    VERIFICATION_PENDING_FOR_GUILD_LIMIT = 1 << 16,
    EMBEDDED_IN_CLIENT = 1 << 17,
    GATEWAY_MESSAGE_CONTENT = 1 << 18,
    GATEWAY_MESSAGE_CONTENT_LIMITED = 1 << 19,
    EMBEDDED_IN_CLIENT_BY_DISCORD = 1 << 20,


    APPLICATION_COMMAND_BADGE = 1 << 23,
    ACTIVE_IN_PAST_MONTH = 1 << 24
}