/* eslint-disable no-unused-vars */
export const enum UserFlags {
    STAFF = 1 << 0,
    PARTNER = 1 << 1,
    HYPESQUAD = 1 << 2,

    BUG_HUNTER_LEVEL_1 = 1 << 3,

    MFA_SMS = 1 << 4,
    PREMIUM_PROMO_DISMISSED = 1 << 5,

    HYPESQUAD_BRAVERY = 1 << 6,
    HYPESQUAD_BRILLIANCE = 1 << 7,
    HYPESQUAD_BALANCE = 1 << 8,

    EARLY_NITRO_BADGE = 1 << 9,
    IS_TEAM = 1 << 10,

    INTERNAL_APPLICATION = 1 << 11,
    SYSTEM = 1 << 12,
    HAS_UNREAD_URGENT_MESSAGES = 1 << 13,

    BUG_HUNTER_LEVEL_2 = 1 << 14,

    UNDERAGE_DELETED = 1 << 15,

    VERIFIED_BOT = 1 << 16,
    VERIFIED_DEVELOPER = 1 << 17,
    CERTIFIED_MODERATOR = 1 << 18,

    BOT_HTTP_INTERACTIONS = 1 << 19,
    SPAMMER = 1 << 20,
    DISABLE_NITRO = 1 << 21,

    ACTIVE_DEVELOPER = 1 << 22,

    // 22 ... 33 unknown

    HIGH_GLOBAL_RATELIMIT = 1 << 33,

    DELETED = 1 << 34,
    DISABLED_FOR_SUSPICIOUS_ACTIVITY = 1 << 35,
    SELF_DELETED = 1 << 36,
    PREMIUM_DISCRIMINATOR = 1 << 37,

    USED_DESKTOP_CLIENT = 1 << 38,
    USED_WEB_CLIENT = 1 << 39,
    USED_MOBILE_CLIENT = 1 << 40,

    DISABLED = 1 << 41,

    VERIFIED_EMAIL = 1 << 43,
    QUARANTINED = 1 << 44,

    STAFF_COLLABORATOR = 1 << 50,
    STAFF_RESTRICTED_COLLABORATOR = 1 << 51,
}

export const enum ChannelFlags {
    GUILD_FEED_REMOVED = 1 << 0,
    PINNED = 1 << 1,
    ACTIVE_CHANNELS_REMOVED = 1 << 2,
    REQUIRE_TAG = 1 << 4,
    SPAM = 1 << 5,
    // 1 << 6
    GUILD_RESOURCE_CHANNEL = 1 << 7,
    CLYDE_AI = 1 << 8,
    SCHEDULED_FOR_DELETION = 1 << 9,
    MEDIA_CHANNEL = 1 << 10,
    SUMMARIES_DISABLED = 1 << 11,
    APPLICATION_SHELF_CONSENT = 1 << 12, // GROUP_DM ONLY
    ROLE_SUBSCRIPTION_TEMPLATE_PREVIEW_CHANNEL = 1 << 12, // GUILD ONLY
}

export const enum ApplicationFlags {
    NONE = 0,
    RELEASED = 1 << 1,
    MANAGED_EMOJI = 1 << 2,
    IN_APP_PURCHASES = 1 << 3,
    CAN_CREATE_GROUP_DMS = 1 << 4,
    RPC_PRIVATE_BETA = 1 << 5,
    USES_AUTOMOD_BADGE = 1 << 6,

    ALLOW_ASSETS = 1 << 8,
    ALLOW_SPECTATING = 1 << 9,
    ALLOW_JOINING = 1 << 10,
    RPC_CONNECTED = 1 << 11,
    GATEWAY_PRESENCE = 1 << 12,
    GATEWAY_PRESENCE_LIMITED = 1 << 13,
    GATEWAY_GUILD_MEMBERS = 1 << 14,
    GATEWAY_GUILD_MEMBERS_LIMITED = 1 << 15,
    VERIFICATION_PENDING_FOR_GUILD_LIMIT = 1 << 16,
    EMBEDDED_IN_CLIENT = 1 << 17,
    GATEWAY_MESSAGE_CONTENT = 1 << 18,
    GATEWAY_MESSAGE_CONTENT_LIMITED = 1 << 19,
    EMBEDDED_IN_CLIENT_BY_DISCORD = 1 << 20,

    APPLICATION_COMMAND_BADGE = 1 << 23,
    ACTIVE_IN_PAST_MONTH = 1 << 24,
}

export const enum MessageFlags {
    CROSSPOSTED = 1 << 0,
    IS_CROSSPOST = 1 << 1,
    SUPPRESS_EMBEDS = 1 << 2,
    SOURCE_MESSAGE_DELETED = 1 << 3,
    URGENT = 1 << 4,
    HAS_THREAD = 1 << 5,
    EPHEMERAL = 1 << 6,
    LOADING = 1 << 7,
    FAILED_TO_MENTION_SOME_ROLES_IN_THREAD = 1 << 8,
    // 1 << 9
    SHOULD_SHOW_LINK_NOT_DISCORD_WARNING = 1 << 10,
    // 1 << 11
    SUPPRESS_NOTIFICATIONS = 1 << 12,
    IS_VOICE_MESSAGE = 1 << 13,
}

export const enum Permissions {
    NONE = 0,
    CREATE_INSTANT_INVITE = 1 << 0,
    KICK_MEMBERS = 1 << 1,
    BAN_MEMBERS = 1 << 2,
    ADMINISTRATOR = 1 << 3,
    MANAGE_CHANNELS = 1 << 4,
    MANAGE_GUILD = 1 << 5,
    ADD_REACTIONS = 1 << 6,
    VIEW_AUDIT_LOG = 1 << 7,
    PRIORITY_SPEAKER = 1 << 8,
    STREAM = 1 << 9,
    VIEW_CHANNEL = 1 << 10,
    SEND_MESSAGES = 1 << 11,
    SEND_TTS_MESSAGES = 1 << 12,
    MANAGE_MESSAGES = 1 << 13,
    EMBED_LINKS = 1 << 14,
    ATTACH_FILES = 1 << 15,
    READ_MESSAGE_HISTORY = 1 << 16,
    MENTION_EVERYONE = 1 << 17,
    USE_EXTERNAL_EMOJIS = 1 << 18,
    VIEW_GUILD_INSIGHTS = 1 << 19,
    CONNECT = 1 << 20,
    SPEAK = 1 << 21,
    MUTE_MEMBERS = 1 << 22,
    DEAFEN_MEMBERS = 1 << 23,
    MOVE_MEMBERS = 1 << 24,
    USE_VAD = 1 << 25,
    CHANGE_NICKNAME = 1 << 26,
    MANAGE_NICKNAMES = 1 << 27,
    MANAGE_ROLES = 1 << 28,
    MANAGE_WEBHOOKS = 1 << 29,
    MANAGE_EXPRESSIONS = 1 << 30,
    USE_APPLICATION_COMMANDS = 1 << 31,
    REQUEST_TO_SPEAK = 1 << 32,
    MANAGE_EVENTS = 1 << 33,
    MANAGE_THREADS = 1 << 34,
    CREATE_PUBLIC_THREADS = 1 << 35,
    CREATE_PRIVATE_THREADS = 1 << 36,
    USE_EXTERNAL_STICKERS = 1 << 37,
    SEND_MESSAGES_IN_THREADS = 1 << 38,
    USE_EMBEDDED_ACTIVITIES = 1 << 39,
    MODERATE_MEMBERS = 1 << 40,
    VIEW_CREATOR_MONETIZATION_ANALYTICS = 1 << 41,
}
